### ISSUE TITLE
The button is visible in smaller width but not in desktop

### ISSUE THREAD

**Issue by upsaurav12** [HimanshuNarware/CareerZunction_Intern#12] opened 2024-05-09 10:51 UTC
**Describe the bug**
In the home page the ``check-now`` button is not visible in desktop width but it is visible in smaller width

**Expected behavior**
The button should visible in all the width length smaller and desktop width 

**Screenshots**
these are the screen shots for the issues
this is desktop width 
![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/116784047/0d61e0e0-852b-4255-8806-9527c2e14dee)

this is smaller width 
![image](https://github.com/HimanshuNarware/CareerZunction_Intern/assets/116784047/fd31cc0b-eb89-45b4-a4a5-35e0e0d1f515)

Example  Fill x { [x] }  into  bracket

- [x] I have checked the existing issues *
- [x] I have read the Contributing Guidelines *
- [x] I have starred the repository *
- [x] Working under Gssoc24*

**Comment by upsaurav12** [comment] 2024-05-09 10:52
Hello all the maintainers i want to work in this issue please assign me under GSSOC 2024

**Comment by HimanshuNarware** [comment] 2024-05-09 13:33
@upsaurav12 it's not a bug, it's a feature, that why am closing this issue,

**Comment by upsaurav12** [comment] 2024-05-09 13:34
ok np

**Closed by HimanshuNarware** 2024-05-09 13:33 UTC
